apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: kyros
spec:
  replicas: 1
  selector:
    matchLabels:
      service: webapp
  template:
    metadata:
      labels:
        app: kyros
        service: webapp
    spec:
      containers:
        - name: webapp
          image: mpraveenraja/busapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 85
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: kyros
    service: webapp
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 85
      protocol: TCP
  selector:
    service: webapp              
